name: snowflake_migration

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pandas
        pip install snowflake
        pip install snowflake-connector-python
        pip install "snowflake-connector-python[pandas]"
        pip install snowflake.sqlalchemy

    - name: Run main.py
      run: python main_code.py
